%% Main script
clc, clear all, close all

dito1_inferiore = importfile("./simulazione/dito1-inferiore.csv", [2, Inf]);
dito2_inferiore = importfile("./simulazione/dito2-inferiore.csv", [2, Inf]);
dito3_inferiore = importfile("./simulazione/dito3-inferiore.csv", [2, Inf]);

dito1_superiore = importfile("./simulazione/dito1-superiore.csv", [2, Inf]);
dito2_superiore = importfile("./simulazione/dito2-superiore.csv", [2, Inf]);
dito3_superiore = importfile("./simulazione/dito3-superiore.csv", [2, Inf]);

% Creazione della figura con tre subplot
figure;

% Primo subplot - Dito 1 (Inferiore e Superiore)
subplot(3,1,1);
plot(dito1_inferiore.Tempo, dito1_inferiore.Forza, 'b-', 'DisplayName', 'Lower Phalanx');
hold on;
plot(dito1_superiore.Tempo, dito1_superiore.Forza, 'r-', 'DisplayName', 'Upper Phalanx');
xlabel('Time [s]');
ylabel('Contact Force [N]');
title('Finger 1')
legend('show');
grid on;
hold off;

% Secondo subplot - Dito 2 (Inferiore e Superiore)
subplot(3,1,2);
plot(dito2_inferiore.Tempo, dito2_inferiore.Forza, 'b-', 'DisplayName', 'Lower Phalanx');
hold on;
plot(dito2_superiore.Tempo, dito2_superiore.Forza, 'r-', 'DisplayName', 'Upper Phalanx');
xlabel('Time [s]');
ylim([0,10]);
ylabel('Contact Force [N]');
title('Finger 2')
legend('show');
grid on;
hold off;

% Terzo subplot - Dito 3 (Inferiore e Superiore)
subplot(3,1,3);
plot(dito3_inferiore.Tempo, dito3_inferiore.Forza, 'b-', 'DisplayName', 'Lower Phalanx');
hold on;
plot(dito3_superiore.Tempo, dito3_superiore.Forza, 'r-', 'DisplayName', 'Upper Phalanx');
xlabel('Time [s]');
ylabel('Contact Force [N]');
title('Finger 3')
legend('show');
grid on;
hold off;


%% Functions 

function results = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  RESULTS = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  RESULTS = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  results = importfile("./simulazione_10_secondi/dito1-inferiore.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Aug-2024 17:35:25

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Tempo", "Forza"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
results = readtable(filename, opts);

end