%% Main script
clc;
clear all;
close all;

% Importazione dei dati
dito1 = importfile("./dito1.csv", [2, Inf]);
dito2 = importfile("./dito2.csv", [2, Inf]);
dito3 = importfile("./dito3.csv", [2, Inf]);

% Calcola la media della forza per ciascun dataset
mean_force1 = mean(dito1.Forza);
mean_force2 = mean(dito2.Forza);
mean_force3 = mean(dito3.Forza);

% Crea vettori per la media della forza con la stessa dimensione della variabile Tempo
mean_force_vector1 = mean_force1 * ones(size(dito1.Tempo));
mean_force_vector2 = mean_force2 * ones(size(dito2.Tempo));
mean_force_vector3 = mean_force3 * ones(size(dito3.Tempo));

% Creazione della figura con tre subplot
figure;

% Primo subplot - Dito 1 (Inferiore e Superiore)
subplot(3,1,1);
plot(dito1.Tempo, dito1.Forza, 'b-', 'DisplayName', 'Experimental Contact Force');
hold on;
plot(dito1.Tempo, mean_force_vector1, 'r-', 'LineWidth', 1.2, 'DisplayName', 'Average Contact Force');
xlabel('Time [s]');
ylabel('Contact Force [N]');
title('Finger 1');
grid on;
legend('Experimental Contact Force', 'Average Contact Force');
hold off;

% Secondo subplot - Dito 2 (Inferiore e Superiore)
subplot(3,1,2);
plot(dito2.Tempo, dito2.Forza, 'b-', 'DisplayName', 'Experimental Contact Force');
hold on;
plot(dito2.Tempo, mean_force_vector2, 'r-', 'LineWidth', 1.2, 'DisplayName', 'Average Contact Force');
xlabel('Time [s]');
ylabel('Contact Force [N]');
title('Finger 2');
grid on;
legend('Experimental Contact Force', 'Average Contact Force');
hold off;

% Terzo subplot - Dito 3 (Inferiore e Superiore)
subplot(3,1,3);
plot(dito3.Tempo, dito3.Forza, 'b-', 'DisplayName', 'Experimental Contact Force');
hold on;
plot(dito3.Tempo, mean_force_vector3, 'r-', 'LineWidth', 1.2, 'DisplayName', 'Average Contact Force');
xlabel('Time [s]');
ylabel('Contact Force [N]');
title('Finger 3');
grid on;
legend('Experimental Contact Force', 'Average Contact Force');
hold off;

%% Functions 

function results = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  RESULTS = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  RESULTS = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  results = importfile("./simulazione_10_secondi/dito1-inferiore.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Aug-2024 17:35:25

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Tempo", "Forza"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
results = readtable(filename, opts);

end